export default {
    "arabic": "Arabic",
    "armenianEastern": "Armenian (Eastern)",
    "armenianWestern": "Armenian (Western)",
    "assamese": "Assamese",
    "balochi": "Balochi",
    "belarusian": "Belarusian",
    "bengali": "Bengali",
    "brazilian": "Brazilian",
    "burmese": "Burmese",
    "chinese": "Chinese",
    "czech": "Czech",
    "english": "English",
    "farsi": "Farsi",
    "french": "French",
    "georgian": "Georgian",
    "german": "German",
    "gilaki": "Gilaki",
    "greek": "Greek",
    "hebrew": "Hebrew",
    "hindi": "Hindi",
    "hungarian": "Hungarian",
    "italian": "Italian",
    "japanese": "Japanese",
    "kannada": "Kannada",
    "korean": "Korean",
    "kurdish": "Kurdish",
    "macedonian": "Macedonian",
    "malayalam": "Malayalam",
    "nigerian": "Nigerian",
    "nko": "N'Ko",
    "norwegian": "Norwegian",
    "odia": "Odia",
    "polish": "Polish",
    "punjabi": "Punjabi",
    "russian": "Russian",
    "russianOld": "Russian (Old)",
    "sindhi": "Sindhi",
    "spanish": "Spanish",
    "swedish": "Swedish",
    "telugu": "Telugu",
    "thai": "Thai",
    "turkish": "Turkish",
    "ukrainian": "Ukrainian",
    "urdu": "Urdu",
    "urduStandard": "Urdu (Standard)",
    "uyghur": "Uyghur"
};